import { Prisma } from '@prisma/client';

export interface MenuSeedData extends Prisma.MenuUncheckedCreateInput {
  id: number;
}

export const menus: MenuSeedData[] = [
  // ==================== 首页 Home [MENU] ====================
  {
    id: 1,
    name: '首页',
    code: 'Home',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/home',
    redirect: null,
    icon: 'fe:home',
    component: '/src/views/home/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: true,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: false },
  },

  // ==================== 系统管理 System [DIRECTORY] ====================
  {
    id: 2,
    name: '系统管理',
    code: 'System',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/system',
    redirect: '/system/user',
    icon: 'fe:layout',
    component: null,
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // -------- 用户管理 User [DIRECTORY] --------
  {
    id: 3,
    name: '用户管理',
    code: 'User',
    permission: null,
    type: 'DIRECTORY',
    pid: 2,
    path: '/system/user',
    redirect: '/system/user/list',
    icon: 'fe:layout',
    component: null,
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 24,
    name: '用户列表',
    code: 'UserList',
    permission: 'system:user:list',
    type: 'MENU',
    pid: 3,
    path: '/system/user/list',
    redirect: null,
    icon: null,
    component: '/src/views/system/user/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 25,
    name: '用户编辑',
    code: 'UserEdit',
    permission: 'system:user:edit',
    type: 'MENU',
    pid: 3,
    path: '/system/user/edit/:id',
    redirect: null,
    icon: null,
    component: '/src/views/system/user/UserEdit.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: false,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // -------- 菜单管理 MenuManager [MENU] --------
  {
    id: 4,
    name: '菜单管理',
    code: 'MenuManager',
    permission: 'system:menu:list',
    type: 'MENU',
    pid: 2,
    path: '/system/menu',
    redirect: null,
    icon: 'solar:checklist-broken',
    component: '/src/views/system/menu/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // -------- 角色管理 Role [MENU] --------
  {
    id: 5,
    name: '角色管理',
    code: 'Role',
    permission: 'system:role:list',
    type: 'MENU',
    pid: 2,
    path: '/system/role',
    redirect: null,
    icon: 'solar:user-speak-outline',
    component: '/src/views/system/role/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // -------- 部门管理 SystemDepartment [MENU] --------
  {
    id: 20,
    name: '部门管理',
    code: 'SystemDepartment',
    permission: 'system:department:list',
    type: 'MENU',
    pid: 2,
    path: '/system/department',
    redirect: null,
    icon: 'mingcute:department-line',
    component: '/src/views/system/department/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // -------- 操作日志 SystemOpLog [MENU] --------
  {
    id: 19,
    name: '操作日志',
    code: 'SystemOpLog',
    permission: 'system:operation-log:list',
    type: 'MENU',
    pid: 2,
    path: '/system/op-log',
    redirect: null,
    icon: 'solar:dialog-2-broken',
    component: '/src/views/system/operation-log/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // -------- 系统配置 SystemConfig [MENU] --------
  {
    id: 13,
    name: '系统配置',
    code: 'SystemConfig',
    permission: 'system:config:list',
    type: 'MENU',
    pid: 2,
    path: '/system/config',
    redirect: null,
    icon: 'material-symbols:settings-outline',
    component: '/src/views/system/config/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 5,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // ==================== 用户管理按钮权限 ====================
  {
    id: 7,
    name: '新增',
    code: 'UserCreate',
    permission: 'system:user:create',
    type: 'BUTTON',
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 31,
    name: '编辑/启用/禁用',
    code: 'UserUpdate',
    permission: 'system:user:update',
    type: 'BUTTON',
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 32,
    name: '删除',
    code: 'UserDelete',
    permission: 'system:user:delete',
    type: 'BUTTON',
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 33,
    name: '分配角色',
    code: 'UserAssignRole',
    permission: 'system:user:assign-role',
    type: 'BUTTON',
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 34,
    name: '重置密码',
    code: 'UserResetPassword',
    permission: 'system:user:reset-password',
    type: 'BUTTON',
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 菜单管理按钮权限 ====================
  {
    id: 35,
    name: '新增',
    code: 'MenuCreate',
    permission: 'system:menu:create',
    type: 'BUTTON',
    pid: 4,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 36,
    name: '修改',
    code: 'MenuUpdate',
    permission: 'system:menu:update',
    type: 'BUTTON',
    pid: 4,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 37,
    name: '删除',
    code: 'MenuDelete',
    permission: 'system:menu:delete',
    type: 'BUTTON',
    pid: 4,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 角色管理按钮权限 ====================
  {
    id: 38,
    name: '新增',
    code: 'RoleCreate',
    permission: 'system:role:create',
    type: 'BUTTON',
    pid: 5,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 39,
    name: '修改',
    code: 'RoleUpdate',
    permission: 'system:role:update',
    type: 'BUTTON',
    pid: 5,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 40,
    name: '删除',
    code: 'RoleDelete',
    permission: 'system:role:delete',
    type: 'BUTTON',
    pid: 5,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 41,
    name: '分配菜单权限',
    code: 'RoleAssignMenu',
    permission: 'system:role:assign-menu',
    type: 'BUTTON',
    pid: 5,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 部门管理按钮权限 ====================
  {
    id: 42,
    name: '新增',
    code: 'DepartmentCreate',
    permission: 'system:department:create',
    type: 'BUTTON',
    pid: 20,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 43,
    name: '修改/启用/禁用',
    code: 'DepartmentUpdate',
    permission: 'system:department:update',
    type: 'BUTTON',
    pid: 20,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 44,
    name: '删除',
    code: 'DepartmentDelete',
    permission: 'system:department:delete',
    type: 'BUTTON',
    pid: 20,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 45,
    name: '分配/移除部门成员',
    code: 'DepartmentAssignUser',
    permission: 'system:department:assign-user',
    type: 'BUTTON',
    pid: 20,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 46,
    name: '分配/移除部门角色',
    code: 'DepartmentAssignRole',
    permission: 'system:department:assign-role',
    type: 'BUTTON',
    pid: 20,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 操作日志按钮权限 ====================
  {
    id: 47,
    name: '删除/清空',
    code: 'OperationLogDelete',
    permission: 'system:operation-log:delete',
    type: 'BUTTON',
    pid: 19,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 系统配置按钮权限 ====================
  {
    id: 48,
    name: '新增',
    code: 'ConfigCreate',
    permission: 'system:config:create',
    type: 'BUTTON',
    pid: 13,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 49,
    name: '修改/启用/禁用',
    code: 'ConfigUpdate',
    permission: 'system:config:update',
    type: 'BUTTON',
    pid: 13,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 50,
    name: '删除',
    code: 'ConfigDelete',
    permission: 'system:config:delete',
    type: 'BUTTON',
    pid: 13,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 公告管理 NoticeManager [DIRECTORY] ====================
  {
    id: 8,
    name: '公告管理',
    code: 'NoticeManager',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/notice',
    redirect: '/notice/notice',
    icon: 'material-symbols:signpost-outline',
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 9,
    name: '公告列表',
    code: 'Notice',
    permission: 'notice:list',
    type: 'MENU',
    pid: 8,
    path: '/notice/notice',
    redirect: null,
    icon: 'iconoir:post',
    component: '/src/views/notice/notice/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 30,
    name: '公告编辑',
    code: 'NoticeEdit',
    permission: null,
    type: 'MENU',
    pid: 8,
    path: '/notice/notice/edit/:id',
    redirect: null,
    icon: null,
    component: '/src/views/notice/notice/noticeEdit.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: false,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 公告按钮权限 ====================
  {
    id: 26,
    name: '新增',
    code: 'NoticeCreate',
    permission: 'notice:create',
    type: 'BUTTON',
    pid: 8,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 27,
    name: '修改/撤回/归档',
    code: 'NoticeUpdate',
    permission: 'notice:update',
    type: 'BUTTON',
    pid: 8,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 28,
    name: '删除',
    code: 'NoticeDelete',
    permission: 'notice:delete',
    type: 'BUTTON',
    pid: 8,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 29,
    name: '发布/下刊',
    code: 'NoticePublish',
    permission: 'notice:publish',
    type: 'BUTTON',
    pid: 8,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 个人中心 UserCenter [MENU] ====================
  {
    id: 6,
    name: '个人中心',
    code: 'UserCenter',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/user-center',
    redirect: null,
    icon: 'solar:user-id-broken',
    component: '/src/views/user-center/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: false },
  },
];
