import { Prisma } from '@prisma/client';

export interface MenuSeedData extends Prisma.MenuUncheckedCreateInput {
  id: number;
}

export const menus: MenuSeedData[] = [
  // ==================== 首页 ====================
  {
    id: 1,
    name: '首页',
    code: 'Home',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/home',
    redirect: null,
    icon: 'fe:home',
    component: '/src/views/home/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: true,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: false },
  },

  // ==================== 系统管理 ====================
  {
    id: 2,
    name: '系统管理',
    code: 'System',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/system',
    redirect: '/system/user',
    icon: 'fe:layout',
    component: null,
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  // -------- 系统管理子菜单 --------
  {
    id: 3,
    name: '用户管理',
    code: 'User',
    permission: null,
    type: 'DIRECTORY',
    pid: 2,
    path: '/system/user',
    redirect: '/system/user/list',
    icon: 'fe:layout',
    component: null,
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 24,
    name: '用户列表',
    code: 'UserList',
    permission: 'system:user:list',
    type: 'MENU',
    pid: 3,
    path: '/system/user/list',
    redirect: null,
    icon: null,
    component: '/src/views/system/user/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 25,
    name: '用户编辑',
    code: 'UserEdit',
    permission: null,
    type: 'MENU',
    pid: 3,
    path: '/system/user/edit/:id',
    redirect: null,
    icon: null,
    component: '/src/views/system/user/UserEdit.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: false,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 4,
    name: '菜单管理',
    code: 'MenuManager',
    permission: 'system:menu:list',
    type: 'MENU',
    pid: 2,
    path: '/system/menu',
    redirect: null,
    icon: 'solar:checklist-broken',
    component: '/src/views/system/menu/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 5,
    name: '角色管理',
    code: 'Role',
    permission: 'system:role:list',
    type: 'MENU',
    pid: 2,
    path: '/system/role',
    redirect: null,
    icon: 'solar:user-speak-outline',
    component: '/src/views/system/role/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 13,
    name: '系统配置',
    code: 'SystemConfig',
    permission: 'system:config:list',
    type: 'MENU',
    pid: 2,
    path: '/system/config',
    redirect: null,
    icon: 'material-symbols:settings-outline',
    component: '/src/views/system/config/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  {
    id: 19,
    name: '操作日志',
    code: 'SystemOpLog',
    permission: 'system:oplog:list',
    type: 'MENU',
    pid: 2,
    path: '/system/op-log',
    redirect: null,
    icon: 'solar:dialog-2-broken',
    component: '/src/views/system/oplog/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 5,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  {
    id: 20,
    name: '部门管理',
    code: 'SystemDepartment',
    permission: 'system:department:list',
    type: 'MENU',
    pid: 2,
    path: '/system/department',
    redirect: null,
    icon: 'mingcute:department-line',
    component: '/src/views/system/department/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  // -------- 用户管理按钮权限 --------
  {
    id: 7,
    name: '新增',
    code: 'UserCreate',
    permission: 'system:user:create',
    type: 'BUTTON',
    pid: 3,
    path: null,
    redirect: null,
    icon: null,
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  // ==================== 个人中心 ====================
  {
    id: 6,
    name: '个人中心',
    code: 'UserCenter',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/user-center',
    redirect: null,
    icon: 'solar:user-id-broken',
    component: '/src/views/user-center/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: false },
  },
  // ==================== 公告管理 ====================
  {
    id: 8,
    name: '公告管理',
    code: 'NoticeManager',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/notice',
    redirect: '/notice/notice',
    icon: 'material-symbols:signpost-outline',
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 9,
    name: '公告',
    code: 'Notice',
    permission: null,
    type: 'MENU',
    pid: 8,
    path: '/notice/notice',
    redirect: null,
    icon: 'iconoir:post',
    component: '/src/views/notice/notice/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 10,
    name: '待办事项',
    code: 'Todo',
    permission: null,
    type: 'MENU',
    pid: 8,
    path: '/notice/todo',
    redirect: null,
    icon: 'vscode-icons:file-type-light-todo',
    component: '/src/views/notice/todo/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: false },
  },
  // ==================== 博客 ====================
  {
    id: 11,
    name: '博客',
    code: 'Blog',
    permission: null,
    type: 'DIRECTORY',
    pid: 23,
    path: '/blog',
    redirect: '/blog/home',
    icon: 'tabler:brand-blogger',
    component: null,
    layout: 'blog',
    keepAlive: false,
    method: null,
    description: '博客系统',
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: true },
  },
  {
    id: 12,
    name: '博客首页',
    code: 'BlogHome',
    permission: null,
    type: 'MENU',
    pid: 11,
    path: '/blog/home',
    redirect: null,
    icon: null,
    component: '/src/views/blog/home/index.vue',
    layout: 'blog',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: true },
  },
  // ==================== 资源库 ====================
  {
    id: 15,
    name: '资源库',
    code: 'Resource',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/resource',
    redirect: '/resource/u3c3',
    icon: 'material-symbols:database-outline',
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: false },
  },
  {
    id: 14,
    name: 'u3c3',
    code: 'U3C3',
    permission: null,
    type: 'MENU',
    pid: 15,
    path: '/resource/u3c3',
    redirect: null,
    icon: 'tabler:subtask',
    component: '/src/views/other/resource/u3c3/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  {
    id: 18,
    name: '爬取日志',
    code: 'U3c3Log',
    permission: null,
    type: 'MENU',
    pid: 15,
    path: '/resource/u3c3_log',
    redirect: null,
    icon: 'material-symbols:3d-rotation',
    component: '/src/views/other/resource/u3c3Log/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  // ==================== 导航管理 ====================
  {
    id: 21,
    name: '导航管理',
    code: 'Navigation',
    permission: null,
    type: 'DIRECTORY',
    pid: 23,
    path: '/navigation',
    redirect: '/navigation/admin',
    icon: 'material-symbols:navigation-outline',
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: true },
  },
  {
    id: 22,
    name: '导航',
    code: 'NavigationAdmin',
    permission: null,
    type: 'MENU',
    pid: 21,
    path: '/navigation/admin',
    redirect: null,
    icon: 'material-symbols:assistant-navigation-outline-rounded',
    component: '/src/views/navigation/admin/index.vue',
    layout: 'public',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: true },
  },
  // ==================== 小诚 ====================
  {
    id: 16,
    name: '小诚',
    code: 'Xiaocheng',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/xiaocheng',
    redirect: '/xiaocheng/task',
    icon: 'material-symbols:accessible-forward-sharp',
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 5,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  {
    id: 17,
    name: '任务列表',
    code: 'XiaochengTask',
    permission: null,
    type: 'MENU',
    pid: 16,
    path: '/xiaocheng/task',
    redirect: null,
    icon: 'material-symbols:task-outline-sharp',
    component: '/src/views/xiaocheng/task/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
  // ==================== 公开页面 ====================
  {
    id: 23,
    name: '公开页面',
    code: 'Public',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/public',
    redirect: null,
    icon: null,
    component: null,
    layout: 'public',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 6,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },
];
