import { Prisma } from '@prisma/client';

export interface MenuSeedData extends Prisma.MenuUncheckedCreateInput {
  id: number;
}

/**
 * 菜单种子数据
 *
 * 同一棵树承载两个投影：
 * - DIRECTORY / MENU：导航层，构成侧边栏与动态路由
 * - BUTTON：权限层，一个按钮即一个接口权限码（permission 字段）
 *
 * 权限码只声明在 BUTTON 行：目录/菜单行的 permission 恒为 null。
 * 运行时鉴权只采集 BUTTON 行；页面可见性取决于角色是否被分配了该 MENU 节点，
 * 两者相互独立，避免出现"勾了页面却拿不到列表接口权限"的误解。
 */
export const menus: MenuSeedData[] = [
  // ==================== 首页 Home [MENU] ====================
  {
    id: 1,
    name: '首页',
    code: 'Home',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/home',
    redirect: null,
    icon: 'fe:home',
    component: '/src/views/home/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: true,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: false,
    extraData: { withContentCard: false },
  },

  // ==================== 系统管理 System [DIRECTORY] ====================
  {
    id: 2,
    name: '系统管理',
    code: 'System',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/system',
    redirect: '/system/user',
    icon: 'fe:layout',
    component: null,
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // -------- 用户管理 User [DIRECTORY] --------
  {
    id: 3,
    name: '用户管理',
    code: 'User',
    permission: null,
    type: 'DIRECTORY',
    pid: 2,
    path: '/system/user',
    redirect: '/system/user/list',
    icon: 'fe:layout',
    component: null,
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 24,
    name: '用户列表',
    code: 'UserList',
    permission: null,
    type: 'MENU',
    pid: 3,
    path: '/system/user/list',
    redirect: null,
    icon: null,
    component: '/src/views/system/user/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 25,
    name: '用户编辑',
    code: 'UserEdit',
    permission: null,
    type: 'MENU',
    pid: 3,
    path: '/system/user/edit/:id',
    redirect: null,
    icon: null,
    component: '/src/views/system/user/UserEdit.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: false,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // -------- 菜单管理 MenuManager [MENU] --------
  {
    id: 4,
    name: '菜单管理',
    code: 'MenuManager',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/menu',
    redirect: null,
    icon: 'solar:checklist-broken',
    component: '/src/views/system/menu/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // -------- 角色管理 Role [MENU] --------
  {
    id: 5,
    name: '角色管理',
    code: 'Role',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/role',
    redirect: null,
    icon: 'solar:user-speak-outline',
    component: '/src/views/system/role/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // -------- 部门管理 SystemDepartment [MENU] --------
  {
    id: 20,
    name: '部门管理',
    code: 'SystemDepartment',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/department',
    redirect: null,
    icon: 'mingcute:department-line',
    component: '/src/views/system/department/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // -------- 操作日志 SystemOpLog [MENU] --------
  {
    id: 19,
    name: '操作日志',
    code: 'SystemOpLog',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/op-log',
    redirect: null,
    icon: 'solar:dialog-2-broken',
    component: '/src/views/system/operation-log/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // -------- 系统配置 SystemConfig [MENU] --------
  {
    id: 13,
    name: '系统配置',
    code: 'SystemConfig',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/config',
    redirect: null,
    icon: 'material-symbols:settings-outline',
    component: '/src/views/system/config/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 5,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // ==================== 公告管理 NoticeManager [DIRECTORY] ====================
  {
    id: 8,
    name: '公告管理',
    code: 'NoticeManager',
    permission: null,
    type: 'DIRECTORY',
    pid: null,
    path: '/notice',
    redirect: '/notice/notice',
    icon: 'material-symbols:signpost-outline',
    component: null,
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 2,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 9,
    name: '公告列表',
    code: 'Notice',
    permission: null,
    type: 'MENU',
    pid: 8,
    path: '/notice/notice',
    redirect: null,
    icon: 'iconoir:post',
    component: '/src/views/notice/notice/index.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 0,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },
  {
    id: 30,
    name: '公告编辑',
    code: 'NoticeEdit',
    permission: null,
    type: 'MENU',
    pid: 8,
    path: '/notice/notice/edit/:id',
    redirect: null,
    icon: null,
    component: '/src/views/notice/notice/NoticeEdit.vue',
    layout: 'normal',
    keepAlive: false,
    method: null,
    description: null,
    show: false,
    enable: true,
    order: 1,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
  },

  // ==================== 个人中心 UserCenter [MENU] ====================
  {
    id: 6,
    name: '个人中心',
    code: 'UserCenter',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/user-center',
    redirect: null,
    icon: 'solar:user-id-broken',
    component: '/src/views/user-center/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 3,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: false },
  },

  // ==================== 数据字典 Dict [MENU] ====================
  {
    id: 58,
    name: '数据字典',
    code: 'Dict',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/dict',
    redirect: null,
    icon: 'material-symbols:book-2-outline',
    component: '/src/views/system/dict/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 6,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // ==================== 待办 Todo [MENU] ====================
  {
    id: 55,
    name: '我的待办',
    code: 'Todo',
    permission: null,
    type: 'MENU',
    pid: null,
    path: '/todo',
    redirect: null,
    icon: 'material-symbols:checklist',
    component: '/src/views/todo/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 4,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // ==================== 前端监控 Metrics [MENU] ====================
  {
    id: 63,
    name: '前端监控',
    code: 'Metrics',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/monitor',
    redirect: null,
    icon: 'material-symbols:monitor-heart-outline',
    component: '/src/views/monitor/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 7,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },

  // ==================== 在线用户 Session [MENU] ====================
  {
    id: 64,
    name: '在线用户',
    code: 'Session',
    permission: null,
    type: 'MENU',
    pid: 2,
    path: '/system/session',
    redirect: null,
    icon: 'material-symbols:group-outline',
    component: '/src/views/system/session/index.vue',
    layout: 'normal',
    keepAlive: true,
    method: null,
    description: null,
    show: true,
    enable: true,
    order: 8,
    isFrame: false,
    frameSrc: null,
    target: '_self',
    affix: false,
    alwaysShow: null,
    badge: null,
    badgeType: null,
    needLogin: true,
    extraData: { withContentCard: true },
  },


  // ==================== 按钮/操作权限（日常由菜单管理界面维护，此处为初始种子） ====================
  {id: 101,name: '新增通知',code: 'notice:create',permission: 'notice:create',type: 'BUTTON',pid: 8,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 102,name: '删除通知',code: 'notice:delete',permission: 'notice:delete',type: 'BUTTON',pid: 8,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 103,name: '查询通知',code: 'notice:list',permission: 'notice:list',type: 'BUTTON',pid: 9,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 104,name: '发布通知',code: 'notice:publish',permission: 'notice:publish',type: 'BUTTON',pid: 8,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 105,name: '编辑通知',code: 'notice:update',permission: 'notice:update',type: 'BUTTON',pid: 8,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 106,name: '新增配置',code: 'system:config:create',permission: 'system:config:create',type: 'BUTTON',pid: 13,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 107,name: '删除配置',code: 'system:config:delete',permission: 'system:config:delete',type: 'BUTTON',pid: 13,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 108,name: '查询配置',code: 'system:config:list',permission: 'system:config:list',type: 'BUTTON',pid: 13,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 109,name: '编辑配置',code: 'system:config:update',permission: 'system:config:update',type: 'BUTTON',pid: 13,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 110,name: '分配角色',code: 'system:department:assign-role',permission: 'system:department:assign-role',type: 'BUTTON',pid: 20,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 111,name: '分配成员',code: 'system:department:assign-user',permission: 'system:department:assign-user',type: 'BUTTON',pid: 20,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 112,name: '新增部门',code: 'system:department:create',permission: 'system:department:create',type: 'BUTTON',pid: 20,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 113,name: '删除部门',code: 'system:department:delete',permission: 'system:department:delete',type: 'BUTTON',pid: 20,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 114,name: '查询部门',code: 'system:department:list',permission: 'system:department:list',type: 'BUTTON',pid: 20,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 115,name: '编辑部门',code: 'system:department:update',permission: 'system:department:update',type: 'BUTTON',pid: 20,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 116,name: '新增字典',code: 'system:dict:create',permission: 'system:dict:create',type: 'BUTTON',pid: 58,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 117,name: '删除字典',code: 'system:dict:delete',permission: 'system:dict:delete',type: 'BUTTON',pid: 58,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 118,name: '查询字典',code: 'system:dict:list',permission: 'system:dict:list',type: 'BUTTON',pid: 58,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 119,name: '编辑字典',code: 'system:dict:update',permission: 'system:dict:update',type: 'BUTTON',pid: 58,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 120,name: '新增菜单',code: 'system:menu:create',permission: 'system:menu:create',type: 'BUTTON',pid: 4,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 121,name: '删除菜单',code: 'system:menu:delete',permission: 'system:menu:delete',type: 'BUTTON',pid: 4,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 122,name: '查询菜单',code: 'system:menu:list',permission: 'system:menu:list',type: 'BUTTON',pid: 4,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 123,name: '编辑菜单',code: 'system:menu:update',permission: 'system:menu:update',type: 'BUTTON',pid: 4,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 124,name: '查询指标',code: 'system:metrics:list',permission: 'system:metrics:list',type: 'BUTTON',pid: 63,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 125,name: '查看监控',code: 'system:monitor:view',permission: 'system:monitor:view',type: 'BUTTON',pid: 63,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 126,name: '删除操作日志',code: 'system:operation-log:delete',permission: 'system:operation-log:delete',type: 'BUTTON',pid: 19,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 127,name: '查询操作日志',code: 'system:operation-log:list',permission: 'system:operation-log:list',type: 'BUTTON',pid: 19,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 128,name: '分配权限',code: 'system:role:assign-menu',permission: 'system:role:assign-menu',type: 'BUTTON',pid: 5,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 129,name: '新增角色',code: 'system:role:create',permission: 'system:role:create',type: 'BUTTON',pid: 5,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 130,name: '删除角色',code: 'system:role:delete',permission: 'system:role:delete',type: 'BUTTON',pid: 5,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 131,name: '查询角色',code: 'system:role:list',permission: 'system:role:list',type: 'BUTTON',pid: 5,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 132,name: '编辑角色',code: 'system:role:update',permission: 'system:role:update',type: 'BUTTON',pid: 5,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 133,name: '强制下线',code: 'system:session:kick',permission: 'system:session:kick',type: 'BUTTON',pid: 64,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 134,name: '查询会话',code: 'system:session:list',permission: 'system:session:list',type: 'BUTTON',pid: 64,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 135,name: '分配角色',code: 'system:user:assign-role',permission: 'system:user:assign-role',type: 'BUTTON',pid: 3,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 136,name: '新增用户',code: 'system:user:create',permission: 'system:user:create',type: 'BUTTON',pid: 3,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 137,name: '删除用户',code: 'system:user:delete',permission: 'system:user:delete',type: 'BUTTON',pid: 3,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 138,name: '查询用户',code: 'system:user:list',permission: 'system:user:list',type: 'BUTTON',pid: 24,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 139,name: '重置密码',code: 'system:user:reset-password',permission: 'system:user:reset-password',type: 'BUTTON',pid: 3,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
  {id: 140,name: '编辑用户',code: 'system:user:update',permission: 'system:user:update',type: 'BUTTON',pid: 3,path: null,redirect: null,icon: null,component: null,layout: 'normal',keepAlive: false,method: null,description: null,show: true,enable: true,order: 0,isFrame: false,frameSrc: null,target: '_self',affix: false,alwaysShow: null,badge: null,badgeType: null,needLogin: true},
];
